### ISSUE TITLE
Invalid type conversion when calling GetObject()

### ISSUE THREAD

**Issue by sheldonkreger** [coming-chat/go-sui-sdk#12]
I am trying to invoke client.GetObject().
`
suiObjectID, err1 := types.NewHexData("0x29623f7e300d1a90ffb925330d2a596608ca8a45")
`
`resp, err2 := cli.GetObject(ctx, suiObjectID)`

Using this syntax, I receive an error:
> cannot use suiObjectID (variable of type *types.HexData) as types.HexData value in argument to cli.GetObjectcompiler[IncompatibleAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#IncompatibleAssign)

In types.go we see:
`type ObjectId = HexData`

So, I expected this syntax to be valid.

What is the correct way to invoke GetObject()? Thanks in advance.

**Comment by Gkirito** [comment]
Are you use this SDK on sui's devnet with the main branch?
Please change to the devnet branch

**Comment by sheldonkreger** [comment]
Thank you for taking a look. I have switched to the devnet branch, but I receive the same error.

**Comment by Gkirito** [comment]
Please use the v2 version and try it again
