### ISSUE TITLE
Multiple Transaction in ExecuteTransactionBlock call

### ISSUE THREAD

**Issue by ripoff2** [coming-chat/go-sui-sdk#18]
How (or if at all) is it possible to pass multiple transactions in an ExecuteTransactionBlock call? Also thank you for your work!

**Comment by Gkirito** [comment]
Using offline build with v2 version
[Relaese v2.0.0](https://github.com/coming-chat/go-sui-sdk/releases/tag/v2.0.0)

**Comment by ripoff2** [comment]
@Gkirito thanks!
