### ISSUE TITLE
Cannot be Installed

### ISSUE THREAD

**Issue by shrimpyuk** [coming-chat/go-sui-sdk#19]
This project cannot be installed as a module currently. Tried about every single combination of ways to try and install it and it will just not work.

`go get github.com/coming-chat/go-sui
go: github.com/coming-chat/go-sui@v0.0.1: parsing go.mod:
        module declares its path as: github.com/coming-chat/go-sui/devnet
                but was required as: github.com/coming-chat/go-sui
`

`go get github.com/coming-chat/go-sui-sdk/devnet   
go: module github.com/coming-chat/go-sui-sdk@upgrade found (v0.0.0-20230328101636-5a5501df2da4), but does not contain package github.com/coming-chat/go-sui-sdk/devnet
`

`go get github.com/coming-chat/go-sui/devnet    
go: module github.com/coming-chat/go-sui@upgrade found (v0.0.1), but does not contain package github.com/coming-chat/go-sui/devnet
`

`go get github.com/coming-chat/go-sui-sdk       
go: github.com/coming-chat/go-sui-sdk@v0.0.0-20230328101636-5a5501df2da4: parsing go.mod:
        module declares its path as: github.com/coming-chat/go-sui
                but was required as: github.com/coming-chat/go-sui-sdk
`

`go get github.com/coming-chat/go-sui-sdk/v1
go: module github.com/coming-chat/go-sui-sdk@upgrade found (v0.0.0-20230328101636-5a5501df2da4), but does not contain package github.com/coming-chat/go-sui-sdk/v1
`

`go get github.com/coming-chat/go-sui-sdk@v1.0.0
go: github.com/coming-chat/go-sui-sdk@v1.0.0: invalid version: go.mod has malformed module path "github.com/coming-chat/go-sui-sdk/v1" at revision v1.0.0
`

`go get github.com/coming-chat/go-sui-sdk/v1@v1.0.0
go: github.com/coming-chat/go-sui-sdk@v1.0.0: invalid version: go.mod has malformed module path "github.com/coming-chat/go-sui-sdk/v1" at revision v1.0.0
`

**Comment by ripoff2** [comment]
@shrimpyuk 
go get github.com/coming-chat/go-sui@devnet

**Comment by shrimpyuk** [comment]
> @shrimpyuk go get github.com/coming-chat/go-sui@devnet

this worked, thankyou! is there any chance you could update the frontpage to mention this?

**Comment by Gkirito** [comment]
Hello everyone, We are happy to tell you that we have upgraded to v2 🎉

[Release v2.0.0](https://github.com/coming-chat/go-sui-sdk/releases/tag/v2.0.0)

**Comment by Gkirito** [comment]
Hello everyone, We are happy to tell you that we have upgraded to v2 🎉
[Release v2.0.0](https://github.com/coming-chat/go-sui-sdk/releases/tag/v2.0.0)
