### ISSUE TITLE
You need demo for TypeArguments []move_types.TypeTag

### ISSUE THREAD

**Issue by ntminh611** [coming-chat/go-sui-sdk#23]
In the Merge pull request https://github.com/coming-chat/go-sui-sdk/pull/22 from coming-chat/feature/support-offile-tx-build
feat: add bcs func withdraw stake, you forgot add some example for TypeArguments []move_types.TypeTag. Would you like add them?

**Comment by Zhangguiguang** [comment]
Because the method called by this MoveCall does not require any `TypeArguments` parameters, I omitted not writing this parameter.

**Comment by ntminh611** [comment]
But in another case, we will need this parameter, can you give me the example how to convert a string to a move_types.TypeTag? 
I my case, I need to use type_arguments: 0x1d58e26e85fbf9ee8596872686da75544342487f95b1773be3c9a49ab1061b19::suia_token::SUIA_TOKEN0x6864a6f921804860930db6ddbe2e16acdf8504495ea7481637a1c8b9a8fe54b::cetus::CETUS
