### ISSUE TITLE
How to convert a string to move_types.TypeTag

### ISSUE THREAD

**Issue by ntminh611** [coming-chat/go-sui-sdk#24]
@Zhangguiguang But in another case, we will need this parameter, can you give me the example how to convert a string to a move_types.TypeTag?
I my case, I need to use type_arguments: 0x1d58e26e85fbf9ee8596872686da75544342487f95b1773be3c9a49ab1061b19::suia_token::SUIA_TOKEN0x6864a6f921804860930db6ddbe2e16acdf8504495ea7481637a1c8b9a8fe54b::cetus::CETUS
<img width="979" alt="image" src="https://github.com/coming-chat/go-sui-sdk/assets/46672883/6cc66e0b-ef27-4cb5-a123-a895f63494c4">

**Comment by thuongtin** [comment]
<img width="833" alt="image" src="https://github.com/coming-chat/go-sui-sdk/assets/3460591/83beff5c-14e6-48e5-8622-78b64441b0b1">

**Comment by Gkirito** [comment]
> @Gkirito
> 
> Is there a way to avoid using versions because they constantly change?

If you use the `SharedObject`, its version was fixed with the number when was created.
But if you use the `ImmOrOwnedObject`, its version was changed by the transaction.
And the transaction data must contain the version of the object. Sui Rpc gets the object version internally, therefore you do not need to offer the version of the object and just offer the object's id.
It's the same with the digest of the object.

``` rust
 let handles: Vec<_> = input_coins
            .into_iter()
            .map(|id| self.get_object_ref(id))
            .collect();
        let mut coin_refs = join_all(handles)
            .await
            .into_iter()
            .collect::<anyhow::Result<Vec<ObjectRef>>>()?;
        // [0] is safe because input_coins is non-empty and coins are of same length as input_coins.
        let gas_object_ref = coin_refs.remove(0);
        let gas_price = self.0.get_reference_gas_price().await?;
        TransactionData::new_pay_sui(
            signer,
            coin_refs,
            recipients,
            amounts,
            gas_object_ref,
            gas_budget,
            gas_price,
        )
```

**Comment by thuongtin** [comment]
@Gkirito You make my day.

**Comment by Gkirito** [comment]
I will temporarily close this issue, but feel free to reopen it if you have any further questions.
