### ISSUE TITLE
BCS Marshal for []byte

### ISSUE THREAD

**Issue by hiendaovinh** [coming-chat/go-sui-sdk#27]
Hi,
For Base64Data, this is how the custom marshaler's defined
```go
func (h Base64Data) MarshalBCS() ([]byte, error) {
    // should be return bcs.Marshal(h) or no custom Marshaler at all
    return h, nil
}
```

I don't think it's compatible to @mystern/sui.js serialization
```js
verifyPersonalMessage(message, signature) {
    return this.verifyWithIntent(
      bcs.ser(["vector", "u8"], message).toBytes(),
      signature,
      IntentScope.PersonalMessage
    );
  }
```

```go
// example
var data lib.Base64Data = []byte{'1'}
bcs.Marshal(data) // [49]
bcs.Marshal([]byte{'1'}) // [1 49] => expected
```

**Comment by Gkirito** [comment]
Thanks for reminding us. It's a historical issue.
In the v1 version, we use `Base64Data` as the `SuiAddress` type, therefore add the custom `MarshalBCS` function(remove the bytes size in the beginning)
``` go
func (h Base64Data) MarshalBCS() ([]byte, error) {
	return h, nil
}
```
Now we have the alone type for SuiAddress as move_types.AccountAddress, accordingly we should recover the Base64Data type, I will open a PR to fix it
