### ISSUE TITLE
is it supported to input vector<Coin<SUI>> arguments ?

### ISSUE THREAD

**Issue by yinwhm12** [coming-chat/go-sui-sdk#29]
Hi, I hope you can help. 
<img width="1373" alt="image" src="https://github.com/coming-chat/go-sui-sdk/assets/25929417/10fab446-81a5-42c0-9b05-ee09ef83ed2d">
is it supported vector<Coin<SUI>> arguments ?
How can I do that? Pls
Looking forward to your reply, thanks.

**Comment by Gkirito** [comment]
Do you want to build offline transactions or use official moveCall RPC?

**Comment by yinwhm12** [comment]
@Gkirito Thank you for your reply.
I use official moveCall RPC and met the problem that how to input the Arg1. pls, give me some ideas.

**Comment by Gkirito** [comment]
E.g from our [wallet-sdk](https://github.com/coming-chat/wallet-SDK/blob/9d3be6f23c86c013c3e893e2c53e42ef3ef5f98e/core/sui/sui_cat.go#L130-L140) the 'pickedCoins.CoinIds()' is an function which returns the list of coin's object_id
``` go 
    func CoinIds() []sui_types.ObjectID 
```

You just put the the list of coin's object_id at index 1

Pseudocode
``` go
client.MoveCall(
    ctx,
    signer,
    packageId,
    "module_name",
    "create", // function_name
    []string{}, // typeArgs
    []any{
        "0xAABBCC", // Arg 0
        []string{
             "0x000AAAABBBBCCC", // coin 1 object id
             "0x000BBBCCC",  //coin 2 object id
             ...
         },  // Arg 1
    }, // args
    gas,
    gasBudget,
}
```
